<?php $redirectUrl = $this->generateUrl(); ?>

<center>
    <iframe src="<?php echo $redirectUrl?>" id="paymentFrame" width="482" height="590" frameborder="0" scrolling="No" ></iframe>

    <script type="text/javascript">
        $(document).ready(function(){
            window.addEventListener('message', function(e) {
                $("#paymentFrame").css("height",e.data['newHeight']+'px');
            }, false);

        });
    </script>
</center>
